### ISSUE TITLE
Desynch prevention/alert + ✅Move card to bottom of the stack feature request

### ISSUE THREAD

**Issue by StellaThimoty** [WE-Kaito/digimon-tcg-simulator#111]
I'm having the game desynch sometimes (usually when one of the players is in wifi). We confirmed it was a desynch as we were vc'ing using Discord. It happened around 2 times during our 5 matches, we were only using collections released in EN if that changes anything. I was playing Ravemon and my opponent (Gaiserick) was using a Greymon toolbox up to BT13 if I'm not mistaken. (In case : ( ) ! + characters might pose any issue)

The first desynch happened when I had my connection stutter, which made sense, but for the subsequent one it didn't since no part had stutters of any kind that we were able to notice.

I checked the logs and couldn't find anything that explained the issue or appointed to it, they seemed normal. Same for the network logs, sorry for leaving you in the dark this time around.
Both players were in Brazil so it might have to do with server distance. 

That issue aside, moving a card to the bottom of a stack would be really great and help with effects such as DNA Digievolving, X antibody (The option), The lv5 Hybrids and Xros decks for example

**Comment by WE-Kaito** [comment]
I experienced this myself when testing on the deployment all the time. Then someone on reddit said, they never had a dc.
Still have no clue what's the issue here, maybe I'll make a poll about it on the next trailer/ reddit post to get an idea how common this problem is.
Since I don't have any prior experience or mentoring on WebSocket implementation, this might be something I need to consult help for. Also experimented with a reconnect, but it doesn't seem to work.

So, how would you suggest moving cards to the bottom of a digimon without hurting the overall convenience?
- Arrows like when you put a card to the decks / security?
- reordering a card like when you drag a hand in your hand your hand?
- ..

**Comment by StellaThimoty** [comment]
I was thinking on how to answer this and I honestly believe that the second option would be the best option due to how trashing from source effects work (New Gomamon line, Tommy Himi, Sourai etc), and other decks such as X Antibody decks and Ragnaloard; that have to constantly reorder their sources.

If the digimon stack was basically another hand, it would be really easy to manipulate it on both adding and removing cards from it, especially when having to use effects that trash sources in order for a digimon not be deleted, while also opening the possibility of moving the entire stack from one field to another (At least I think)

In case those aren't really possible, the third option seems to encompass all other scenarios with more ease than manually doing everything again, with each digimon having it's own field

**Comment by WE-Kaito** [comment]
Alright, thx for that, it was also the most simple change 👌
