### ISSUE TITLE
Effect activation and target indicator

### ISSUE THREAD

**Issue by Nehalem95** [WE-Kaito/digimon-tcg-simulator#186]
First of all, thank you for all the work done; it is greatly appreciated.

I have 2 suggestions that I think may work:

1- A target indicator that allows you to point out an opponent's card that is affected by one of your Digimon's skills. Something like "Targeting Agumon" should also be automatically recorded in the log.

2- A simple way to select one of your cards and indicate that you will use its skill, perhaps by displaying an animation on the card and presenting it in the center of the screen. Something like "Agumon skill" should also be automatically logged.

Both changes are aimed at minimizing the use of the chat, making the game faster and more comfortable, and avoiding the need to type things like "Agumon eff" or "delete Gabumon" in the chat. I believe that something like this would be highly appreciated, particularly by mobile users.

I apologize if you don't understand something, English is not my native language.

**Comment by staticdraq** [comment]
Great suggestions. I've come to Github to make the same suggestion.

Also, it would be great if you can highlight/dim cards.

For example, you can highlight a card to show that it's effect is active. And you can dim a card to show that it's effect is consumed.

Pinging or shaking items in general would be very useful. I'm currently dragging cards just like I'm attacking in order to do ping noise. Demonstrating I'm activating something like a Memory Boost! for example. (Untap has the shake option I'm talking about)
